# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/chat_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChatWindow(object):
    def setupUi(self, ChatWindow):
        ChatWindow.setObjectName("ChatWindow")
        ChatWindow.resize(1000, 600)
        self.centralwidget = QtWidgets.QWidget(ChatWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.mainLayout.setObjectName("mainLayout")
        self.leftPanel = QtWidgets.QFrame(self.centralwidget)
        self.leftPanel.setMinimumSize(QtCore.QSize(220, 20))
        self.leftPanel.setMaximumSize(QtCore.QSize(220, 16777215))
        self.leftPanel.setStyleSheet("\n"
"        background-color: #F4F6FA;\n"
"        border-right: 1px solid #CCCCCC;\n"
"       ")
        self.leftPanel.setObjectName("leftPanel")
        self.leftLayout = QtWidgets.QVBoxLayout(self.leftPanel)
        self.leftLayout.setObjectName("leftLayout")
        self.userLabel = QtWidgets.QLabel(self.leftPanel)
        self.userLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.userLabel.setStyleSheet("font-weight: bold; font-size: 14px;")
        self.userLabel.setObjectName("userLabel")
        self.leftLayout.addWidget(self.userLabel)
        self.userList = QtWidgets.QListWidget(self.leftPanel)
        self.userList.setStyleSheet("\n"
"           QListWidget {\n"
"            background: white;\n"
"            border: none;\n"
"           }\n"
"           QListWidget::item:selected {\n"
"            background-color: #4A90E2;\n"
"            color: white;\n"
"           }\n"
"          ")
        self.userList.setObjectName("userList")
        self.leftLayout.addWidget(self.userList)
        self.groupLabel = QtWidgets.QLabel(self.leftPanel)
        self.groupLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.groupLabel.setStyleSheet("font-weight: bold; font-size: 14px;")
        self.groupLabel.setObjectName("groupLabel")
        self.leftLayout.addWidget(self.groupLabel)
        self.groupList = QtWidgets.QListWidget(self.leftPanel)
        self.groupList.setStyleSheet("\n"
"                       QListWidget {\n"
"                           background: white;\n"
"                           border: none;\n"
"                       }\n"
"                       QListWidget::item:selected {\n"
"                           background-color: #4A90E2;\n"
"                           color: white;\n"
"                       }\n"
"                   ")
        self.groupList.setObjectName("groupList")
        self.leftLayout.addWidget(self.groupList)
        self.btnCreateGroup = QtWidgets.QPushButton(self.leftPanel)
        self.btnCreateGroup.setStyleSheet("\n"
"           QPushButton {\n"
"            background-color: #4CAF50;\n"
"            color: white;\n"
"            border-radius: 8px;\n"
"            padding: 6px 12px;\n"
"            font-weight: bold;\n"
"           }\n"
"           QPushButton:hover {\n"
"            background-color: #45A049;\n"
"           }\n"
"          ")
        self.btnCreateGroup.setObjectName("btnCreateGroup")
        self.leftLayout.addWidget(self.btnCreateGroup, 0, QtCore.Qt.AlignHCenter)
        self.mainLayout.addWidget(self.leftPanel)
        self.chatPanel = QtWidgets.QFrame(self.centralwidget)
        self.chatPanel.setStyleSheet("\n"
"        background-color: #FFFFFF;\n"
"       ")
        self.chatPanel.setObjectName("chatPanel")
        self.chatLayout = QtWidgets.QVBoxLayout(self.chatPanel)
        self.chatLayout.setObjectName("chatLayout")
        self.chatHeader = QtWidgets.QFrame(self.chatPanel)
        self.chatHeader.setStyleSheet("\n"
"           background-color: #EAEAEA;\n"
"           padding: 8px;\n"
"          ")
        self.chatHeader.setObjectName("chatHeader")
        self.headerLayout = QtWidgets.QHBoxLayout(self.chatHeader)
        self.headerLayout.setSpacing(10)
        self.headerLayout.setObjectName("headerLayout")
        self.leftHeaderLayout = QtWidgets.QHBoxLayout()
        self.leftHeaderLayout.setSpacing(10)
        self.leftHeaderLayout.setObjectName("leftHeaderLayout")
        self.chatAvatar = QtWidgets.QLabel(self.chatHeader)
        self.chatAvatar.setMinimumSize(QtCore.QSize(60, 60))
        self.chatAvatar.setMaximumSize(QtCore.QSize(60, 60))
        self.chatAvatar.setScaledContents(True)
        self.chatAvatar.setStyleSheet("border-radius: 30px;")
        self.chatAvatar.setObjectName("chatAvatar")
        self.leftHeaderLayout.addWidget(self.chatAvatar)
        self.chatTitle = QtWidgets.QLabel(self.chatHeader)
        self.chatTitle.setAlignment(QtCore.Qt.AlignVCenter)
        self.chatTitle.setStyleSheet("font-size: 20px; font-weight: bold;")
        self.chatTitle.setObjectName("chatTitle")
        self.leftHeaderLayout.addWidget(self.chatTitle)
        self.headerLayout.addLayout(self.leftHeaderLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.headerLayout.addItem(spacerItem)
        self.rightHeaderLayout = QtWidgets.QHBoxLayout()
        self.rightHeaderLayout.setSpacing(8)
        self.rightHeaderLayout.setObjectName("rightHeaderLayout")
        self.btnCall = QtWidgets.QPushButton(self.chatHeader)
        self.btnCall.setStyleSheet("\n"
"                QPushButton { background-color: #4CAF50; color: white; border-radius: 8px; padding: 4px 8px; }\n"
"                QPushButton:hover { background-color: #45A049; }\n"
"               ")
        self.btnCall.setObjectName("btnCall")
        self.rightHeaderLayout.addWidget(self.btnCall)
        self.btnVideo = QtWidgets.QPushButton(self.chatHeader)
        self.btnVideo.setStyleSheet("\n"
"                QPushButton { background-color: #2196F3; color: white; border-radius: 8px; padding: 4px 8px; }\n"
"                QPushButton:hover { background-color: #1976D2; }\n"
"               ")
        self.btnVideo.setObjectName("btnVideo")
        self.rightHeaderLayout.addWidget(self.btnVideo)
        self.btnLeaveGroup = QtWidgets.QPushButton(self.chatHeader)
        self.btnLeaveGroup.setStyleSheet("\n"
"                QPushButton { background-color: #f44336; color: white; border-radius: 8px; padding: 4px 8px; }\n"
"                QPushButton:hover { background-color: #d32f2f; }\n"
"               ")
        self.btnLeaveGroup.setObjectName("btnLeaveGroup")
        self.rightHeaderLayout.addWidget(self.btnLeaveGroup)
        self.headerLayout.addLayout(self.rightHeaderLayout)
        self.chatLayout.addWidget(self.chatHeader)
        self.scrollArea = QtWidgets.QScrollArea(self.chatPanel)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollContent = QtWidgets.QWidget()
        self.scrollContent.setObjectName("scrollContent")
        self.chatMessages = QtWidgets.QVBoxLayout(self.scrollContent)
        self.chatMessages.setSpacing(6)
        self.chatMessages.setObjectName("chatMessages")
        self.scrollArea.setWidget(self.scrollContent)
        self.chatLayout.addWidget(self.scrollArea)
        self.inputFrame = QtWidgets.QFrame(self.chatPanel)
        self.inputFrame.setObjectName("inputFrame")
        self.inputLayout = QtWidgets.QHBoxLayout(self.inputFrame)
        self.inputLayout.setObjectName("inputLayout")
        self.messageInput = QtWidgets.QLineEdit(self.inputFrame)
        self.messageInput.setStyleSheet("\n"
"              border: 1px solid #CCCCCC;\n"
"              border-radius: 8px;\n"
"              padding: 6px;\n"
"             ")
        self.messageInput.setObjectName("messageInput")
        self.inputLayout.addWidget(self.messageInput)
        self.btnImage = QtWidgets.QPushButton(self.inputFrame)
        self.btnImage.setStyleSheet("\n"
"              QPushButton {\n"
"               background-color: #FFA500;\n"
"               color: white;\n"
"               border-radius: 8px;\n"
"               padding: 6px 12px;\n"
"              }\n"
"              QPushButton:hover {\n"
"               background-color: #FFB733;\n"
"              }\n"
"             ")
        self.btnImage.setObjectName("btnImage")
        self.inputLayout.addWidget(self.btnImage)
        self.btnFile = QtWidgets.QPushButton(self.inputFrame)
        self.btnFile.setStyleSheet("\n"
"              QPushButton {\n"
"               background-color: #4CAF50;\n"
"               color: white;\n"
"               border-radius: 8px;\n"
"               padding: 6px 12px;\n"
"              }\n"
"              QPushButton:hover {\n"
"               background-color: #45A049;\n"
"              }\n"
"             ")
        self.btnFile.setObjectName("btnFile")
        self.inputLayout.addWidget(self.btnFile)
        self.btnVoice = QtWidgets.QPushButton(self.inputFrame)
        self.btnVoice.setObjectName("btnVoice")
        self.inputLayout.addWidget(self.btnVoice)
        self.chatLayout.addWidget(self.inputFrame)
        self.mainLayout.addWidget(self.chatPanel)
        ChatWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ChatWindow)
        QtCore.QMetaObject.connectSlotsByName(ChatWindow)

    def retranslateUi(self, ChatWindow):
        _translate = QtCore.QCoreApplication.translate
        ChatWindow.setWindowTitle(_translate("ChatWindow", "Chat Application"))
        self.userLabel.setText(_translate("ChatWindow", "Xin chào, username"))
        self.groupLabel.setText(_translate("ChatWindow", "Nhóm"))
        self.btnCreateGroup.setText(_translate("ChatWindow", "+ Tạo nhóm"))
        self.chatTitle.setText(_translate("ChatWindow", "Chat chung"))
        self.btnCall.setText(_translate("ChatWindow", "📞"))
        self.btnVideo.setText(_translate("ChatWindow", "🎥"))
        self.btnLeaveGroup.setText(_translate("ChatWindow", "🚪"))
        self.messageInput.setPlaceholderText(_translate("ChatWindow", "Nhập tin nhắn..."))
        self.btnImage.setText(_translate("ChatWindow", "🖼️"))
        self.btnFile.setText(_translate("ChatWindow", "📁"))
        self.btnVoice.setText(_translate("ChatWindow", "🎤"))
