# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(800, 450)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftFrame = QtWidgets.QFrame(self.centralwidget)
        self.leftFrame.setMinimumSize(QtCore.QSize(300, 0))
        self.leftFrame.setStyleSheet("background-color: #FFFFFF;\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;")
        self.leftFrame.setObjectName("leftFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.leftFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.logoLabel = QtWidgets.QLabel(self.leftFrame)
        self.logoLabel.setMinimumSize(QtCore.QSize(300, 300))
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setObjectName("logoLabel")
        self.verticalLayout_2.addWidget(self.logoLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 300, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.leftFrame)
        self.rightFrame = QtWidgets.QFrame(self.centralwidget)
        self.rightFrame.setStyleSheet("background-color: #F5F6FA;")
        self.rightFrame.setObjectName("rightFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.rightFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(self.rightFrame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel, 0, QtCore.Qt.AlignHCenter)
        self.nameInput = QtWidgets.QLineEdit(self.rightFrame)
        self.nameInput.setStyleSheet("QLineEdit {\n"
" border: 1px solid #D0D0D0;\n"
" border-radius: 8px;\n"
" padding: 8px;\n"
" background-color: white;\n"
"}")
        self.nameInput.setObjectName("nameInput")
        self.verticalLayout.addWidget(self.nameInput)
        self.passwordInput = QtWidgets.QLineEdit(self.rightFrame)
        self.passwordInput.setStyleSheet("QLineEdit {\n"
" border: 1px solid #D0D0D0;\n"
" border-radius: 8px;\n"
" padding: 8px;\n"
" background-color: white;\n"
"}")
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.verticalLayout.addWidget(self.passwordInput)
        self.signInButton = QtWidgets.QPushButton(self.rightFrame)
        self.signInButton.setStyleSheet("QPushButton {\n"
" background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #4A90E2, stop:1 #357ABD);\n"
" color: white;\n"
" border-radius: 20px;\n"
" padding: 10px 20px;\n"
" font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
" background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #5AA0F2, stop:1 #468BDC);\n"
"}")
        self.signInButton.setObjectName("signInButton")
        self.verticalLayout.addWidget(self.signInButton, 0, QtCore.Qt.AlignHCenter)
        self.signUpButton = QtWidgets.QPushButton(self.rightFrame)
        self.signUpButton.setStyleSheet("QPushButton {\n"
" background-color: transparent;\n"
" color: #357ABD;\n"
" border: none;\n"
" text-decoration: underline;\n"
"}\n"
"QPushButton:hover {\n"
" color: #5AA0F2;\n"
"}")
        self.signUpButton.setObjectName("signUpButton")
        self.verticalLayout.addWidget(self.signUpButton, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.rightFrame)
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Sign In"))
        self.titleLabel.setText(_translate("LoginWindow", "Welcome Back!"))
        self.nameInput.setPlaceholderText(_translate("LoginWindow", "Username"))
        self.passwordInput.setPlaceholderText(_translate("LoginWindow", "Password"))
        self.signInButton.setText(_translate("LoginWindow", "Sign In"))
        self.signUpButton.setText(_translate("LoginWindow", "Don\'t have an account? Sign Up"))
